[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "wso-docs"

[output.html]
default-theme = "ephelia"
preferred-dark-theme = "ayu"
additional-css = ["./theme/ephelia.css"]
git-repository-url = "https://github.com/nsflores1/wso-docs"
